name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlab >=4.0.5,<5.0
  - pip:
    - jupyterlite===0.2.0a4
    - jupyterlite-xeus-python==1.0.0a0
    - jupyterlite_javascript_kernel===0.2.0a4
