name: build-env
channels:
  - conda-forge
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge/noarch
dependencies:
  - python===3.11
  - pip
  - jupyterlab >=4.0.7,<5.0
  - ply
  - pygtrie
  - tenacity
  - pydantic
  - idna
  - jupyterlab-filesystem-access~=0.5.3
  - pip:
    - jupyterlite==0.2.0
    - jupyterlite-xeus-python==1.0.0a3
    - jupyterlite_javascript_kernel==0.2.0
    - jupyterlite_pyodide_kernel===0.2.0a2
    # - jupyter-collaboration==2.0.0alpha4
    - ipycanvas
    - numpy
    - matplotlib
    - seaborn
    - plotnine
    - pandas
    - ipywidgets
    - jupyterlab-visualpython
    - jsonpath-ng
    - nest_asyncio
    # - './wheels/*.whl' does NOT work
    - './wheels/multidict-6.0.4-py3-none-any.whl'
    - './wheels/tornado-6.3.3-py3-none-any.whl'
    - './wheels/frozenlist-1.4.0-py3-none-any.whl'
    - './wheels/aiohttp-3.8.5-py3-none-any.whl'
    - './wheels/jupyterlab_examples_completer-0.1.0-py3-none-any.whl'
    - langchain
    # - './wheels/jupyter_ai_magics-2.3.0-py3-none-any.whl'
    # - './wheels/jupyter_ai-2.3.0-py3-none-any.whl'
    # - './wheels/guidance-0.0.64-py3-none-any.whl'
    # - './wheels/yarl-1.9.2-py3-none-any.whl'
    - AzureOpenAI
    - OpenAI
    - chapyter
    - jupyter_ai
    - chapyter
