name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - python===3.10
  - ipycanvas
  - numpy
  - matplotlib
  - seaborn
  - plotnine
  - pandas
  - ipywidgets
  - ply
  - pygtrie
  - tenacity
  - pydantic
  - idna
  - requests
  # - pip:
  #   - './wheels/async_timeout-4.0.3-py3-none-any.whl'
  #   - charset-normalizer
  #   - jsonpath-ng
  #   - ipycanvas
  #   - jupyterlab-visualpython
  #   - python-dotenv
  #   - './wheels/multidict-6.0.4-py3-none-any.whl'
  #   - './wheels/tornado-6.3.3-py3-none-any.whl'
  #   - './wheels/frozenlist-1.4.0-py3-none-any.whl'
  #   - './wheels/aiohttp-3.8.5-py3-none-any.whl'
  #   - langchain==0.0.309
  #   - './wheels/jupyter_ai_magics-2.2.0-py3-none-any.whl'
  #   - './wheels/jupyter_ai_monorepo-2.2.0-py3-none-any.whl'
  #   - './wheels/guidance-0.0.64-py3-none-any.whl'
  #   - AzureOpenAI
  #   - OpenAI
  #   - chapyter
  #   - jupyter_ai
  #   - nest_asyncio
  #   - './wheels/yarl-1.9.2-py3-none-any.whl'
  # - multidict
  # - tornado
  # - aiohttp
  # - langchain
  # - jupyter-ai
  # - numexpr This one has no available package!
  # - statsmodels
  # - scikit-learn
  # - scipy
  # - sqlite
  # - bokeh
  # - panel
  # - altair
  # - ipympl
  # - ipyleaflet
  # - ipydatagrid
  # - ipycanvas
  # - vega_datasets
  # - plotly
  # - bqplot
  # - black
  # - pyviz_comms
  # - openpyxl
  # - python-tzdata
  # - httpx
  # - xarray
