name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - ipycanvas
  - numpy
  - matplotlib
  - seaborn
  - plotnine
  - pandas
  # - multidict
  # - tornado
  # - aiohttp
  # - langchain
  # - jupyter-ai
  # - numexpr This one has no available package!
  # - statsmodels
  # - scikit-learn
  # - scipy
  # - sqlite
  # - bokeh
  # - panel
  # - altair
  # - ipympl
  # - ipyleaflet
  # - ipydatagrid
  # - ipycanvas
  # - vega_datasets
  # - plotly
  # - bqplot
  # - black
  # - pyviz_comms
  # - openpyxl
  # - python-tzdata
  # - httpx
  # - xarray
